version: "3.8"
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    healthcheck:
      test: "/opt/rabbitmq/sbin/rabbitmqctl status"
      interval: 2s
      timeout: 30s
      retries: 15

  calculator:
    build: calculator_ms/
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:192.168.0.13"
    depends_on:
      - rabbitmq

  multiply:
    build: multiply_ms/
    ports:
      - "8081:8080"
    extra_hosts:
      - "localhost:192.168.0.13"
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  divide:
    build: divide_ms/
    ports:
      - "8082:8080"
    extra_hosts:
      - "localhost:192.168.0.13"
    depends_on:
      rabbitmq:
        condition: service_healthy

  add:
    build: add_ms/
    ports:
      - "8083:8080"
    extra_hosts:
      - "localhost:192.168.0.13"
    depends_on:
      rabbitmq:
        condition: service_healthy

  subtract:
    build: subtract_ms/
    ports:
      - "8084:8080"
    extra_hosts:
      - "localhost:192.168.0.13"
    depends_on:
      rabbitmq:
        condition: service_healthy
